### ISSUE TITLE
Input Capture not working in Plasma 6.1

### ISSUE THREAD

**Issue by xf-** [feschber/lan-mouse#140]
Log entry
```
lan_mouse::emulate] wayland backend not available: the requested global was not found in the registry
```

I tried wayland to wayland.

**Comment by feschber** [comment]
This log is unrelated. Did you update xdg-desktop-portal-kde as well?

**Comment by xf-** [comment]
yes - xdg-desktop-portal-kde 6.0.90-1

**Comment by feschber** [comment]
Ah I just noticed: they apparently implemented the input-capture portal. So that's interesting. I will have to test that later!

**Comment by xf-** [comment]
I'm not in a hurry, just reported the issue. It is still a beta.

**Comment by feschber** [comment]
Got around to testing this. I am getting valid barriers but not receiving any input events... Will have to see if thats a kwin bug or what else is going on here.

**Comment by feschber** [comment]
Update: Got in contact with KDE devs. Should be fixed in 6.1.1 it was a type mismatch in dbus

**Comment by feschber** [comment]
Okay TLDR:

Plasma 6.1.0 introduced the input-capture portal, i.e. the "frontend" to libei.
Previously, the layer-shell backend was used as a fallback, which is basically a 1px wide window that grabbed the mouse on the edge of the screen.

Now with the plasma input capture portal there were two issues:

- [x] Plasma used a wrong type in serialization, causing deserialization to fail in [ashpd](https://github.com/bilelmoussaoui/ashpd). This is now fixed in 6.1.1 after I reported it.

- [ ] The second issue is that plasma does not (yet?) report `barrier_ids`, when input capture is activated.
This is an **optional** addition of the spec, however I expected it to be implemented, which is not the case but keep in mind, this is **not** a plasma bug so please dont report bugs ;).
The Input Capture Portal works by defining "barriers" and giving them an id. Then, when input capture is activated, The compositor reports the position and _optionally_ a barrier id, which I can use to check  which barrier was activated (i.e. which lan-mouse client).

There is several ways to go about this:
- Wait for plasma to implement `barrier_ids` & only support one client until this is done
- Add the option to fallback to the layer-shell capture backend (I'd still prefer this to be a fallback)
- Work around barrier_ids by calculating the activated barrier from the activation position of the cursor

Nr. 3 is probably the most favourable.

**Comment by xf-** [comment]
Is the second issue 6.1.1 input (mouse, keyboard) freezes as soon as I touch edge?

**Comment by DrYak** [comment]
@xf- : yup exactly. (My setup suffers the same).

**Comment by feschber** [comment]
The specific reason, why its getting stuck is actually because ashpd does not yet correctly handle the case of no barrier_id being sent.
Its already fixed but not yet in a new release.

**Comment by xf-** [comment]
> The specific reason, why its getting stuck is actually because ashpd does not yet correctly handle the case of no barrier_id being sent. Its already fixed but not yet in a new release.

I build the main branch and I had the issue. You mean committed and pushed towards main or a git release?

**Comment by feschber** [comment]
No, the barrier_id is fixed in the ashpd main branch. It still requires a workaround in lan-mouse and an update of ashpd after there is a new ashpd release.

**Comment by feschber** [comment]
You can now set
```toml
capture_backend = "LayerShell"
```
in `config.toml` as a workaround

**Comment by DrYak** [comment]
(Any ETA when you could tag a new release with `capture_backend` ?)

**Comment by xf-** [comment]
> You can now set
> 
> ```toml
> capture_backend = "LayerShell"
> ```
> 
> in `config.toml` as a workaround

Didn't work, maybe I added it in wrong spot, but via cli argument it works :)

**Comment by feschber** [comment]
It should go on the top of the file

**Comment by feschber** [comment]
This should now be fixed.
Unfortunately, there seems to be an issue with the "cursor shake" desktop effect on plasma, which results in a captured cursor appearing visible again, so please be aware of that ;)

https://bugs.kde.org/show_bug.cgi?id=490495

**Comment by DrYak** [comment]
(Any  ETA when you'll tag the fixed version, so I update the TumbleWeed package to not omit the InputCapture backend anymore?)

**Comment by feschber** [comment]
I want to do some more testing and make sure I didnt break anything. I'll do my best to finish that this weekend

**Comment by feschber** [comment]
@DrYak  I updated the release ;)
