### ISSUE TITLE
Lan-mouse continues to run after exiting GUI with no way to re-open.

### ISSUE THREAD

**Issue by CupricReki** [feschber/lan-mouse#38]
Lan-mouse continues to run in the background after closing the GUI with no taskbar icon. Adding an option to close/minimize to taskbar would be great.

Wayland
KDE Plasma 5.27.9

**Comment by feschber** [comment]
Yes, I'm aware of this.

The reason, it currently works like this is because I'm not fully decided on whether I should split lan-mouse into separate binaries for the Gui and the actual service that talks with the compositor for input emulation / capture. This would however add the extra step of launching the service which I want to avoid.

Ideally it should be transparent to the user such that on first startup the service is started and then keeps running until someone explicitly disables it (you may have noticed that the enable switch does not work yet). Subsequent instances of would then only launch the Gui and talk to the service.

This approach would require the background desktop portal or a systemd user service. I'm still figuring out what's best here.

The infrastructure for reattaching the service to a new gui is already in place so bare with me here :)

**Comment by CupricReki** [comment]
Seems very logical that there should be a separate systemd service. While the service is running, there should be a taskbar icon as well which launches the GUI.
