### ISSUE TITLE
Client not responding, releasing pointer!

### ISSUE THREAD

**Issue by xf-** [feschber/lan-mouse#69]
I tried a lot of things, but I can't get it to work

**Setup**
X11 -> Wayland
Wayland -> X11
Wayland -> Wayland

Both systems use KDE, libei installed, xdg-dekstop-portal...

**Error**
```
INFO  lan_mouse::dns] dnsname: adding ip 192.168.12.123
WARN  lan_mouse::server] client not responding, releasing pointer!
```
Error occurs if I try to enter the other screen. Did most tests from Wayland to Wayland. Also, I selected `Yes` for permission `Input devices`

**Comment by feschber** [comment]
Okay so device a) should have device b) added and activated and device b) should have device a) added and activated.

If it still doesn't work, you likely have to enable udp port 4242 in your firewall.

**Comment by xf-** [comment]
I got it running, I always tried a server/client setup, so I run the connection only on one side. Now I started `Connections` them on both and it works. I'm switched from barrier and was used to that setup.

**Comment by feschber** [comment]
Good to hear!

**Comment by VPavliashvili** [comment]
@xf-  Hello
sorry asking on closed thread, but I have same error and could not resolve in any way. Can you share your solution/config with me please? been trying this for several hours. Also I am trying to make this work on hyprland->hyprland

**Comment by feschber** [comment]
Hi @VPavliashvili , did you configure both devices? You need to add and activate the corresponding device on both sides (this is not yet done automatically).

Otherwise, could  you send a debug log from both sides? You do not need a config file at all for this.

You can generate one by running with `LAN_MOUSE_LOG_LEVEL=debug` like this:

```sh
LAN_MOUSE_LOG_LEVEL=debug cargo run
```

And just in case: Do you have a firewall running? If that is the case, check that you have [configured the firewall](https://github.com/feschber/lan-mouse#manual-installation)

**Comment by VPavliashvili** [comment]
Hi @feschber, thanks for your time
here are logs for both hosts, the files are named accordingly
[host_dorthonion.log](https://github.com/feschber/lan-mouse/files/14923752/host_dorthonion.log)
[host_parthGalen.log](https://github.com/feschber/lan-mouse/files/14923753/host_parthGalen.log)

These are output of `LAN_MOUSE_LOG_LEVEL=debug cargo run` command and both are run without config.toml files at $XDG_HOME_CONFIG. I can provide logs with config files if you need too.

Also I could not understand client and host relationship here since both machine seems to be client and host at the same time and can you clarify that what does exactly client and host mean in terms of this software?

As for firewall, firewalld was running only on one machine(on parthGalen in particular) and I configured it accordingly

**Comment by feschber** [comment]
I dont see any `AddClient` and `Activate` requests in `host_dorthonion.log`.
You need to add parthGalen on that client and activate it as well.

**Comment by feschber** [comment]
And `dorthonion` can apparently not be resolved. Please check that your hostname is correct. (`cat /etc/hostname` should give you the correct hostname)

**Comment by VPavliashvili** [comment]
I have added parthGalen on dorthonion. And I have added dorthonion on parthGalen. I am certain that host names are correct but still getting could not resolve host warning messages. I have no idea what to do tbh

**Comment by feschber** [comment]
can you check if they can be manually resolved via `nslookup dorthonion` / `nslookup parthGalen`?

**Comment by VPavliashvili** [comment]
apparently this is the output for both cases
`** server can't find parthGalen: NXDOMAIN`
`** server can't find dorthonion: NXDOMAIN`
I don't know how this stuff works but I can say that both machiens are on the same wifi router's network

**Comment by feschber** [comment]
You know how the saying goes? “it’s always dns”. Unfortunately I can not really help you with this. You should figure out, why dns can not resolve your hosts.

You can however still use lan-mouse if you configure the ip addresses in `~/.config/lan-mouse/config.toml` something like this:
```toml
# dorthonion
[right]
hostname = "parthGalen"
ips = [ "<ip-of-parthGalen>" ]
```

```toml
# parthGalen
[left]
hostname = "dorthonion"
ips = [ "<ip-of-dorthonion>" ]
```

**Comment by VPavliashvili** [comment]
Oh yes it finally worked after configuring it right and disabling firewall on parthGalen. Thank you so much for your help and your time.

**Comment by feschber** [comment]
no problem, glad I could help!
